# https://docs.docker.com/compose/compose-file/compose-file-v3
version: '3.8'

services:
  # https://hub.docker.com/_/postgres
  postgres:
    image: 'postgres:13.4-alpine'
    ports:
      - '5432:5432'
    volumes:
      - './build/docker/postgres:/docker-entrypoint-initdb.d'
      - 'postgres-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      PGTZ: 'UTC'
      TZ: 'UTC'

  # https://hub.docker.com/_/adminer
  adminer:
    image: 'adminer:latest'
    ports:
      - '2000:8080'
    links:
      - postgres
    depends_on:
      - postgres

volumes:
  postgres-data:
